FROM node:18-alpine

# Instala python3 y pip
RUN apk add --no-cache python3 py3-pip

WORKDIR /app/backend

COPY . .

RUN if [ -f package.json ]; then npm install; fi

EXPOSE 3000 3001 3002 3003 3005 3007 3008 3009 3010

CMD pip3 install --no-cache-dir -r scripts/requirements.txt && npm start